version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context:  ./frontend
    ports:
      - "5000:80"
  
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8080:8080"