version: "3"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context:  ./frontend
    ports:
      - "5000:80"
  
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '8001:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data